In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data=pd.read_csv(r'C:\Users\Ganesh\Desktop\jupiter\Fake news detection\train.csv',skip_blank_lines=True,engine='c',encoding='latin1')

In [4]:
data.head()

id                                              title              author  \
0  0  House Dem Aide: We Didn’t Even See Comey’s...       Darrell Lucus   
1  1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2  2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3  2                                                NaN                 NaN   
4  3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s...    1.0  
1  Ever get the feeling your life circles the rou...    0.0  
2  Why the Truth Might Get You Fired October 29, ...    1.0  
3                                                NaN    NaN  
4  Videos 15 Civilians Killed In Single US Airstr...    1.0

In [5]:
# cheacking the shape of dataframe
data.shape

(20888, 5)

In [6]:
# cheacking the nulll values
data.isnull().sum()

id          80
title      641
author    2041
text       125
label      168
dtype: int64

In [7]:
# creating the copy of dataframe 
df=data.copy()

In [8]:
# droping the null values
df.dropna(inplace=True)

In [9]:
df.shape

(18209, 5)

In [10]:
df.head()

id                                              title              author  \
0  0  House Dem Aide: We Didn’t Even See Comey’s...       Darrell Lucus   
1  1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2  2                  Why the Truth Might Get You Fired  Consortiumnews.com   
4  3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
6  4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s...    1.0  
1  Ever get the feeling your life circles the rou...    0.0  
2  Why the Truth Might Get You Fired October 29, ...    1.0  
4  Videos 15 Civilians Killed In Single US Airstr...    1.0  
6  Print \nAn Iranian woman has been sentenced to...    1.0

In [14]:
# here we reshape bcz we have deleted the null value 
df.reset_index(inplace=True)

In [15]:
df.head()

index id                                              title  \
0      0  0  House Dem Aide: We Didn’t Even See Comey’s...   
1      1  1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2  2                  Why the Truth Might Get You Fired   
3      4  3  15 Civilians Killed In Single US Airstrike Hav...   
4      6  4  Iranian woman jailed for fictional unpublished...   

               author                                               text  \
0       Darrell Lucus  House Dem Aide: We Didn’t Even See Comey’s...   
1     Daniel J. Flynn  Ever get the feeling your life circles the rou...   
2  Consortiumnews.com  Why the Truth Might Get You Fired October 29, ...   
3     Jessica Purkiss  Videos 15 Civilians Killed In Single US Airstr...   
4      Howard Portnoy  Print \nAn Iranian woman has been sentenced to...   

   label  
0    1.0  
1    0.0  
2    1.0  
3    1.0  
4    1.0

In [16]:
# here we only consider 'title' feature for the prediction
X=df['title']
y=df['label']


In [19]:
# here we can see the unexpected value in label so we replace with some label
y.value_counts()

0.0     10324
1.0      7884
38.0        1
Name: label, dtype: int64

In [23]:
def num(x):
    if x==0:
        return 0
    return 1
y=y.map(num)

In [24]:
y.value_counts()

0    10324
1     7885
Name: label, dtype: int64

In [25]:
# now we do some data cleaning
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
import re
corpus=[]

for i in range(len(X)):
    news=re.sub('[^a-zA-Z]',' ',X[i])
    news=news.lower()
    news=news.split()
    news=[ps.stem(word) for word in news if not word in stopwords.words('english')]
    news=' '.join(news)
    corpus.append(news)



In [109]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hillari',
 'chuck todd buzzfe donald trump polit favor breitb

In [33]:
# importing TfIdf
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf=TfidfVectorizer(max_features=5000,ngram_range=(1,3))
X=tfidf.fit_transform(corpus).toarray()

In [34]:
# cheacking the shape of X
X.shape

(18209, 5000)

In [35]:
# cheacking the shape of y
y.shape

(18209,)

In [36]:
# spliting the dataset in train and test
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.3,random_state=42)

In [39]:
# cheacking some features name
tfidf.get_feature_names()[:10]

['abandon',
 'abc',
 'abc news',
 'abduct',
 'abe',
 'abedin',
 'abl',
 'abort',
 'abroad',
 'absolut']

In [40]:
#cheacking the parametres
tfidf.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.float64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': 5000,
 'min_df': 1,
 'ngram_range': (1, 3),
 'norm': 'l2',
 'preprocessor': None,
 'smooth_idf': True,
 'stop_words': None,
 'strip_accents': None,
 'sublinear_tf': False,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'use_idf': True,
 'vocabulary': None}

# MultinomialNB Algorithm

In [41]:
# now we importing naive_bayes model
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import MultinomialNB
nvb=MultinomialNB()
nvb.fit(xtrain,ytrain)
pred=nvb.predict(xtest)
acc=accuracy_score(ytest,pred)*float(100)
acc

87.99194581731649

here is the accuracy arround 88%

# Confusion Matrix

In [49]:
# ploting the confussion matrix
from sklearn.metrics import confusion_matrix,plot_confusion_matrix

con=confusion_matrix(ytest,pred)
con

array([[2915,  187],
       [ 469, 1892]], dtype=int64)

# Hyperparameter tunning

In [55]:
previous_score=0
for alpha in np.arange(0,1,0.1):
    nvb=MultinomialNB(alpha=alpha)
    nvb.fit(xtrain,ytrain)
    pred=nvb.predict(xtest)
    score = accuracy_score(ytest, pred)
    if score>previous_score:
        classifier=nvb
    print("Alpha: {}, Score : {}".format(alpha,score))

C:\python\lib\site-packages\sklearn\naive_bayes.py:512: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  'setting alpha = %.1e' % _ALPHA_MIN)


Alpha: 0.0, Score : 0.8683873329672341
Alpha: 0.1, Score : 0.8791872597473915
Alpha: 0.2, Score : 0.8793703093538349
Alpha: 0.30000000000000004, Score : 0.8813838550247117
Alpha: 0.4, Score : 0.8822991030569284
Alpha: 0.5, Score : 0.8826652022698152
Alpha: 0.6000000000000001, Score : 0.8830313014827018
Alpha: 0.7000000000000001, Score : 0.8819330038440417
Alpha: 0.8, Score : 0.8815669046311551
Alpha: 0.9, Score : 0.8806516565989383


# Using LSTM

In [60]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from tensorflow.keras.preprocessing.sequence import pad_sequences 
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot

In [98]:
# first defind dictionory size

vec_size=5000


In [97]:
# defined sentence length
sen_length=20

# Onehot representation

In [99]:
onehot=[one_hot(words,vec_size) for words in corpus]

In [100]:
# getting index form dictionory
print(onehot)

[[1606, 3803, 2448, 4279, 2879, 3933, 1600, 701, 2284, 3195], [3832, 2506, 2813, 2910, 4567, 1038, 900], [1080, 1842, 4305, 1392], [3693, 629, 1138, 4900, 2182, 2657], [1699, 4567, 4511, 3098, 2742, 592, 4567, 4127, 4028, 2153], [1746, 3378, 4070, 3158, 4606, 3828, 1348, 655, 1448, 1566, 2112, 4018, 896, 2711, 900], [1064, 2948, 643, 985, 2976, 1444, 4799, 1277, 2717, 4992, 4190], [2742, 1749, 2105, 238, 4934, 1682, 3828, 4385, 2717, 4992, 4190], [4667, 1803, 4525, 3626, 3786, 2491, 265, 3037, 3828, 1545], [1558, 4354, 1771, 2438, 1583, 175, 399, 3584], [2697, 3721, 610, 4296, 3722, 369, 4711, 2235, 532, 1053, 356], [4900, 2696, 2879, 2491, 3828, 4934], [2616, 791, 108, 3003, 2339, 4799, 1705, 2717, 4992, 4190], [1055, 4493, 2420, 2454, 3638, 2717, 4992, 4190], [2711, 1862, 2458, 4248, 4610, 268, 2784, 264, 1325, 3826], [1307, 2863, 2506], [1981, 1981, 3514, 3385, 3828, 2170, 2688, 900], [805, 1134, 2813, 2902, 2527, 3896, 1313, 1553, 592], [1145, 2493, 3828, 2111, 2608, 900], [2547, 4

# Word Embedding representation

In [101]:
# to get equal length we use padding
seq_pad=pad_sequences(onehot,padding='pre',maxlen=20)
print(seq_pad)

[[   0    0    0 ...  701 2284 3195]
 [   0    0    0 ... 4567 1038  900]
 [   0    0    0 ... 1842 4305 1392]
 ...
 [   0    0    0 ... 2717 4992 4190]
 [   0    0    0 ... 3052  332  505]
 [   0    0    0 ... 1817  748  924]]


In [102]:
# define the feature size i.e diamention
dim=40

In [103]:
# initialize the model
model=Sequential()
model.add(Embedding(vec_size,dim,input_length=sen_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
lstm_1 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [104]:
len(onehot),y.shape

(18209, (18209,))

In [105]:
# convert onehot into array
import numpy as np
X_final=np.array(seq_pad)
y_final=np.array(y)

In [106]:
X_final.shape,y_final.shape

((18209, 20), (18209,))

In [119]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.30, random_state=20)

In [120]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Train on 12746 samples, validate on 5463 samples
Epoch 1/10
12746/12746 [==============================] - 15s 1ms/sample - loss: 0.3515 - accuracy: 0.8316 - val_loss: 0.1830 - val_accuracy: 0.9213
Epoch 2/10
12746/12746 [==============================] - 9s 720us/sample - loss: 0.1541 - accuracy: 0.9412 - val_loss: 0.1782 - val_accuracy: 0.9259
Epoch 3/10
12746/12746 [==============================] - 9s 713us/sample - loss: 0.1199 - accuracy: 0.9575 - val_loss: 0.1873 - val_accuracy: 0.9240
Epoch 4/10
12746/12746 [==============================] - 9s 718us/sample - loss: 0.0966 - accuracy: 0.9653 - val_loss: 0.2106 - val_accuracy: 0.9253
Epoch 5/10
12746/12746 [==============================] - 9s 720us/sample - loss: 0.0776 - accuracy: 0.9733 - val_loss: 0.2328 - val_accuracy: 0.9248
Epoch 6/10
12746/12746 [==============================] - 9s 716us/sample - loss: 0.0682 - accuracy: 0.9762 - val_loss: 0.2647 - val_accuracy: 0.9158
Epoch 7/10
12746/12746 [============================

In [121]:
y_pred=model.predict_classes(X_test)
confusion_matrix(y_test,y_pred)

array([[2843,  255],
       [ 190, 2175]], dtype=int64)

In [122]:

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.918542925132711

In [123]:
#Adding Dropout
from tensorflow.keras.layers import Dropout
## Creating model
model=Sequential()
model.add(Embedding(vec_size,dim,input_length=sen_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
dropout_2 (Dropout)          (None, 20, 40)            0         
_________________________________________________________________
lstm_3 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dropout_3 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [124]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Train on 12746 samples, validate on 5463 samples
Epoch 1/10
12746/12746 [==============================] - 15s 1ms/sample - loss: 0.3397 - accuracy: 0.8453 - val_loss: 0.1840 - val_accuracy: 0.9213
Epoch 2/10
12746/12746 [==============================] - 9s 715us/sample - loss: 0.1563 - accuracy: 0.9381 - val_loss: 0.1869 - val_accuracy: 0.9218
Epoch 3/10
12746/12746 [==============================] - 10s 768us/sample - loss: 0.1190 - accuracy: 0.9551 - val_loss: 0.1898 - val_accuracy: 0.9195
Epoch 4/10
12746/12746 [==============================] - 10s 780us/sample - loss: 0.0912 - accuracy: 0.9663 - val_loss: 0.2171 - val_accuracy: 0.9229
Epoch 5/10
12746/12746 [==============================] - 10s 764us/sample - loss: 0.0716 - accuracy: 0.9720 - val_loss: 0.2412 - val_accuracy: 0.9195
Epoch 6/10
12746/12746 [==============================] - 10s 747us/sample - loss: 0.0538 - accuracy: 0.9802 - val_loss: 0.2791 - val_accuracy: 0.9231
Epoch 7/10
12746/12746 [========================

In [125]:
y_pred=model.predict_classes(X_test)

In [126]:
y_pred=model.predict_classes(X_test)
confusion_matrix(y_test,y_pred)

array([[2832,  266],
       [ 207, 2158]], dtype=int64)

In [127]:

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9134175361522973